version: '2.1'

volumes:
  postgres_data: {}
  prometheus_data: {}
  grafana_data: {}

services:

  postgres:
    image: postgres:9.6
    container_name: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jbpm
      POSTGRES_USER: jbpm
      POSTGRES_PASSWORD: jbpm

  jbpm:
    image: jboss/jbpm-server-full:7.59.0.Final
    container_name: jbpm
    environment:
      JBPM_DB_DRIVER: postgres
      JBPM_DB_HOST: postgres
    expose:
    - 8080
    - 8001
    depends_on:
    - postgres

  nginx:
    image: nginx:1.21.3-alpine
    container_name: nginx
    volumes:
    - ./nginx:/etc/nginx/conf.d/
    ports:
    - 80:80
    depends_on:
    - jbpm

  prometheus:
    image: prom/prometheus:v2.8.0
    container_name: prom
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    expose:
      - 9090
    depends_on:
      - jbpm

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100

  grafana:
    image: grafana/grafana:8.2.0
    depends_on:
      - prometheus
    container_name: grafana
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    expose:
      - 3000



